import { Link } from "react-router-dom";
import { ArrowUpRight, BookOpen } from "lucide-react";
import { useEffect, useState } from "react";
import api from "@/lib/api";

const TAG_COLORS = {
  "Case study": { bg: "#EEE9FF", fg: "#4B2FE0" },
  "Growth deep-dive": { bg: "#DFF7EE", fg: "#1A5F4A" },
  "default": { bg: "#F5EFDD", fg: "#8A5F16" },
};

export default function CaseStudies({ slug, caseStudies }) {
  const [publishedContent, setPublishedContent] = useState([]);
  const [loadedContent, setLoadedContent] = useState(false);

  useEffect(() => {
    let ignore = false;
    setLoadedContent(false);
    api
      .get(`/business/public/${slug}/content`)
      .then(({ data }) => {
        if (ignore) return;
        setPublishedContent(data?.posts || []);
      })
      .catch(() => {
        if (!ignore) setPublishedContent([]);
      })
      .finally(() => {
        if (!ignore) setLoadedContent(true);
      });
    return () => {
      ignore = true;
    };
  }, [slug]);

  const stories = publishedContent.length > 0 ? publishedContent.map(contentPostToStory) : caseStudies || [];

  if (!stories.length && loadedContent) return null;
  if (!stories.length) return null;

  return (
    <section id="stories" className="max-w-[1320px] mx-auto px-6 lg:px-10 py-10 lg:py-14" data-testid="case-studies-section">
      <div className="flex items-end justify-between mb-8 flex-wrap gap-4">
        <div>
          <span className="u-pill"><span className="u-pill-dot" /> 04 · stories</span>
          <h2 className="font-display text-3xl lg:text-[2.75rem] font-semibold tracking-tight mt-3 max-w-2xl leading-[1.05]">
            Reviews, rewritten as <span className="font-serif-italic">stories</span>.
          </h2>
          <p className="mt-3 text-[color:var(--u-muted)] max-w-xl text-sm leading-relaxed">
            Uplaud AI reads your review corpus and turns the highest-signal ones into shareable case studies. On-brand. On-message. Zero writing.
          </p>
        </div>
        <span className="hidden md:inline-flex items-center gap-2 text-xs u-pill">
          <BookOpen size={13} /> Generated by Uplaud AI · human approved
        </span>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {stories.map((cs, i) => {
          const tag = TAG_COLORS[cs.tag] || TAG_COLORS.default;
          return (
            <Link
              key={cs.id}
              to={`/business/public/${slug}/blog/${cs.slug}`}
              className="u-card p-6 group flex flex-col reveal relative overflow-hidden"
              style={{ animationDelay: `${i * 0.06}s` }}
              data-testid={`case-study-card-${cs.slug}`}
            >
              <div
                className="absolute -top-16 -right-16 w-40 h-40 rounded-full opacity-0 group-hover:opacity-100 transition duration-500"
                style={{ background: `radial-gradient(closest-side, ${tag.bg}, transparent 70%)` }}
              />
              <div className="flex items-center justify-between mb-5 relative">
                <span
                  className="inline-flex items-center px-2.5 py-1 rounded-full text-[11px] font-medium"
                  style={{ background: tag.bg, color: tag.fg }}
                >
                  {cs.tag}
                </span>
                <span className="text-[11px] text-[color:var(--u-muted)]">{cs.read_time}</span>
              </div>

              <h3 className="font-display text-xl font-semibold leading-[1.15] tracking-tight relative">
                {cs.title}
              </h3>

              <p className="mt-3 text-sm text-[color:var(--u-muted)] leading-relaxed relative flex-1">
                {cs.excerpt}
              </p>

              <blockquote className="mt-5 pt-5 border-t border-[color:var(--u-line)] relative">
                <p className="font-serif-italic text-[15px] leading-snug text-[color:var(--u-ink)]">
                  “{cs.hero_quote}”
                </p>
                <cite className="not-italic block mt-2 text-[11px] text-[color:var(--u-muted)]">
                  — {cs.hero_quote_author}
                </cite>
              </blockquote>

              <div className="mt-5 inline-flex items-center gap-1.5 text-sm font-medium text-[color:var(--u-ink)] relative">
                Read the story
                <ArrowUpRight size={15} className="transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
              </div>
            </Link>
          );
        })}
      </div>
    </section>
  );
}

function contentPostToStory(post) {
  return {
    id: post.id || post.slug,
    slug: post.slug,
    title: post.title,
    excerpt: post.excerpt || post.meta_description,
    tag: post.content_type || "Buyer guide",
    read_time: estimateReadTime(post.content_html),
    hero_quote: post.buyer_question || post.meta_description || post.excerpt || "",
    hero_quote_author: "Uplaud Content Agent",
  };
}

function estimateReadTime(contentHtml) {
  const text = (contentHtml || "").replace(/<[^>]+>/g, " ");
  const words = text.trim().split(/\s+/).filter(Boolean).length;
  return `${Math.max(1, Math.ceil(words / 220))} min read`;
}
